Task: Register
ng-anhhtuann/QuickResponse pull request #12
Opened 2022-06-23 15:56 UTC by ng-anhhtuann

+ Registermethod:  checking duplicated userName and INSERT to MySQL database
+ User: add timeRegister and timeLogin

2022-06-23 15:58 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Model/User.java
> +    public User(String userName, String fullName, int age, boolean gender, String password, String id, String accessToken, String timeRegister) {
timeRegister should be Long

2022-06-23 15:58 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +        SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
What if we can create a new util for datetime helper?

2022-06-23 15:59 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                insertStatement.setString(8, newUser.getTimeRegister());
1, 2,3 ,.... is too hard to understand while we need to maintain in the future. 
Could we find a new way to determine the key column as a name-string?

2022-06-23 16:00 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                e.printStackTrace();
Any logic code in Exception here?

2022-06-23 16:01 UTC, uranashel44 requested changes
LGTM but you need to resolve and reply my confuse first

2022-06-23 16:14 UTC, ng-anhhtuann commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                        true, 200, new DataRegisterStatus(
bad request will be return

2022-06-23 16:30 UTC, ng-anhhtuann commented on src/main/java/com/api/QuickResponse/Model/User.java
> +    public User(String userName, String fullName, int age, boolean gender, String password, String id, String accessToken, String timeRegister) {
okay

2022-06-23 16:42 UTC, ng-anhhtuann commented on src/main/java/com/api/QuickResponse/Controllers/RegisterMethod.java
> -    public Object register(@RequestBody ItemRegister itemRegister) {
it is required and the pack return in exception will be fixed

2022-06-24 06:59 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                insertStatement.setString(row++, newUser.getTimeRegister());
What the heck? =))

2022-06-24 06:59 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                toReturn = new ErrorRegister(e.getMessage(), 100, false);
Right!

2022-06-24 06:59 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                toReturn = new ErrorRegister(e.getMessage(), 100, false);
Ok

2022-06-24 07:00 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +        if (itemRegister==null){
Format yet?

2022-06-24 07:01 UTC, ng-anhhtuann commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                insertStatement.setString(row++, newUser.getTimeRegister());
no other way @@, this is actually better

2022-06-24 07:01 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                insertStatement.setString(8, newUser.getTimeRegister());
It such a damn idea =)) 
Any ways to change the setString or setInt with key, no need to use number I meant

2022-06-24 07:02 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
> +                insertStatement.setString(row++, newUser.getTimeRegister());
Okay, just leave "No way" is enough, why not just leave the message to resolve rather than use the bad way =))

2022-06-25 09:49 UTC, uranashel44 commented on src/main/java/com/api/QuickResponse/Repository/QuickResponseRepository.java
>      }
This class has been updated looks good. Great! 
Clearly comments and descriptions

2022-06-25 09:49 UTC, uranashel44 approved these changes

2022-06-25 09:52 UTC, merged